<?php
$products = array (
  1 => array('titre'=>'Barbies Anna & Elsa', 'prix'=>'35€', 'image'=>'image/elsaetanna.jpg', 'descriptif'=>' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut imperdiet risus. In dignissim leo at ligula pretium tincidunt. Aliquam efficitur mi eu ornare malesuada. Sed hendrerit ac augue a efficitur. Fusce dui ex, laoreet egestas augue non, accumsan mollis quam. In ac luctus ex, eu luctus quam. Nunc interdum vel mauris id feugiat. Mauris posuere sollicitudin arcu, eu lacinia urna lobortis in. Sed in turpis consectetur, convallis tortor non, fermentum arcu. Proin eget efficitur lorem, at volutpat nibh. Suspendisse potenti. In ut tempor est, nec laoreet nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec efficitur eget nibh in consectetur. Cras maximus neque eget quam porta, ultrices tempus dolor blandit. Integer vel lectus auctor, scelerisque nulla interdum, sagittis velit.

Ut tincidunt turpis arcu, at varius ligula eleifend mattis. Phasellus id felis dui. Etiam hendrerit non quam a mollis. Aenean ullamcorper, mauris aliquet viverra posuere, turpis arcu feugiat diam, nec pellentesque turpis nulla sit amet ligula. In sed turpis pellentesque, ultricies nunc non, vulputate turpis. Ut egestas cursus quam, sit amet egestas augue iaculis eget. Aenean venenatis mollis enim, lobortis convallis odio hendrerit non. Ut nibh odio, congue eu ligula non, sagittis fermentum arcu. Pellentesque at pharetra mauris. Nunc non rutrum diam, sed ultrices orci. Nullam feugiat aliquam tellus, convallis malesuada felis accumsan ut. Vivamus ut tortor vehicula, convallis elit at, commodo justo. Sed vel sollicitudin leo. Nulla in turpis consectetur, euismod arcu sit amet, porttitor lacus. '),

  2 => array('titre'=>'Déguisement Anna', 'prix'=>'55€', 'image'=>'image/robe.jpg', 'descriptif'=>' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut imperdiet risus. In dignissim leo at ligula pretium tincidunt. Aliquam efficitur mi eu ornare malesuada. Sed hendrerit ac augue a efficitur. Fusce dui ex, laoreet egestas augue non, accumsan mollis quam. In ac luctus ex, eu luctus quam. Nunc interdum vel mauris id feugiat. Mauris posuere sollicitudin arcu, eu lacinia urna lobortis in. Sed in turpis consectetur, convallis tortor non, fermentum arcu. Proin eget efficitur lorem, at volutpat nibh. Suspendisse potenti. In ut tempor est, nec laoreet nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec efficitur eget nibh in consectetur. Cras maximus neque eget quam porta, ultrices tempus dolor blandit. Integer vel lectus auctor, scelerisque nulla interdum, sagittis velit.

Ut tincidunt turpis arcu, at varius ligula eleifend mattis. Phasellus id felis dui. Etiam hendrerit non quam a mollis. Aenean ullamcorper, mauris aliquet viverra posuere, turpis arcu feugiat diam, nec pellentesque turpis nulla sit amet ligula. In sed turpis pellentesque, ultricies nunc non, vulputate turpis. Ut egestas cursus quam, sit amet egestas augue iaculis eget. Aenean venenatis mollis enim, lobortis convallis odio hendrerit non. Ut nibh odio, congue eu ligula non, sagittis fermentum arcu. Pellentesque at pharetra mauris. Nunc non rutrum diam, sed ultrices orci. Nullam feugiat aliquam tellus, convallis malesuada felis accumsan ut. Vivamus ut tortor vehicula, convallis elit at, commodo justo. Sed vel sollicitudin leo. Nulla in turpis consectetur, euismod arcu sit amet, porttitor lacus. '),

  3 => array('titre'=>'Brosse à cheveux', 'prix'=>'15€', 'image'=>'image/brosse.jpg', 'descriptif'=>' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut imperdiet risus. In dignissim leo at ligula pretium tincidunt. Aliquam efficitur mi eu ornare malesuada. Sed hendrerit ac augue a efficitur. Fusce dui ex, laoreet egestas augue non, accumsan mollis quam. In ac luctus ex, eu luctus quam. Nunc interdum vel mauris id feugiat. Mauris posuere sollicitudin arcu, eu lacinia urna lobortis in. Sed in turpis consectetur, convallis tortor non, fermentum arcu. Proin eget efficitur lorem, at volutpat nibh. Suspendisse potenti. In ut tempor est, nec laoreet nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec efficitur eget nibh in consectetur. Cras maximus neque eget quam porta, ultrices tempus dolor blandit. Integer vel lectus auctor, scelerisque nulla interdum, sagittis velit.

Ut tincidunt turpis arcu, at varius ligula eleifend mattis. Phasellus id felis dui. Etiam hendrerit non quam a mollis. Aenean ullamcorper, mauris aliquet viverra posuere, turpis arcu feugiat diam, nec pellentesque turpis nulla sit amet ligula. In sed turpis pellentesque, ultricies nunc non, vulputate turpis. Ut egestas cursus quam, sit amet egestas augue iaculis eget. Aenean venenatis mollis enim, lobortis convallis odio hendrerit non. Ut nibh odio, congue eu ligula non, sagittis fermentum arcu. Pellentesque at pharetra mauris. Nunc non rutrum diam, sed ultrices orci. Nullam feugiat aliquam tellus, convallis malesuada felis accumsan ut. Vivamus ut tortor vehicula, convallis elit at, commodo justo. Sed vel sollicitudin leo. Nulla in turpis consectetur, euismod arcu sit amet, porttitor lacus. ')
  );
?>
